import os
from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI


# ==========================
# Environment Setup
# ==========================

# Load API credentials from the project's .env file
load_dotenv()

API_KEY = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")


# ==========================
# LangChain Gemini Model
# ==========================

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash",
    google_api_key=API_KEY,
    temperature=0
)


# ==========================
# Helper Function
# ==========================

def extract_text_content(content):
    """
    Converts LangChain/Gemini response content into plain text.

    Gemini may return either:
    - a normal string, or
    - a list of content blocks containing text.
    """

    if isinstance(content, str):
        return content

    if isinstance(content, list):
        text_parts = []

        for block in content:
            if isinstance(block, dict):
                text = block.get("text", "")
                if text:
                    text_parts.append(text)

            elif isinstance(block, str):
                text_parts.append(block)

        return "\n".join(text_parts)

    return str(content)


# ==========================
# Reflection / Critic Step
# ==========================

def reflect_on_analysis(job, user_skills, initial_analysis):
    """
    Critiques the initial job-match analysis.

    The critic checks whether the analysis contains
    unsupported, invented, or inconsistent information.
    """

    reflection_prompt = f"""
You are a critic reviewing an AI-generated job match analysis.

JOB TITLE:
{job.get("title")}

JOB DESCRIPTION:
{job.get("description")}

CANDIDATE SKILLS:
{", ".join(user_skills)}

INITIAL ANALYSIS:
{initial_analysis}

Review the initial analysis carefully.

Check the following:

1. Did the analysis invent any candidate skills or experience?
2. Are the listed matching skills actually provided by the candidate?
3. Are the missing or desired skills supported by the job description?
4. Is the match score reasonable based on the available evidence?
5. Is the explanation consistent with the candidate skills and job requirements?

Return exactly one of these decisions:

DECISION: APPROVE

or

DECISION: REVISE

Then provide:

FEEDBACK:
Briefly explain why the analysis should be approved or revised.

Choose APPROVE if the analysis is accurate, consistent,
and supported by the provided information.

Choose REVISE if the analysis contains invented,
unsupported, or inconsistent information.
"""

    response = llm.invoke(reflection_prompt)

    return extract_text_content(response.content)


# ==========================
# Refinement Step
# ==========================

def refine_analysis(
    job,
    user_skills,
    initial_analysis,
    reflection
):
    """
    Refines the initial analysis using feedback
    generated by the Reflection/Critic step.
    """

    refinement_prompt = f"""
You are refining an AI-generated job match analysis.

JOB TITLE:
{job.get("title")}

JOB DESCRIPTION:
{job.get("description")}

CANDIDATE SKILLS:
{", ".join(user_skills)}

INITIAL ANALYSIS:
{initial_analysis}

CRITIC FEEDBACK:
{reflection}

Revise the initial analysis using the critic feedback.

Return the corrected analysis in this format:

1. Match Score: a number from 0 to 100
2. Matching Skills
3. Missing or Desired Skills
4. Short Explanation

Follow these rules:

- Do not invent candidate skills.
- Do not invent candidate experience.
- Matching skills must come from the provided candidate skills.
- Missing or desired skills must be supported by the job description.
- The match score must be consistent with the evidence.
- Keep the explanation concise and evidence-based.
"""

    response = llm.invoke(refinement_prompt)

    return extract_text_content(response.content)


# ==========================
# Complete Reflection Workflow
# ==========================

def apply_reflection(
    job,
    user_skills,
    initial_analysis
):
    """
    Runs the complete Reflection workflow:

    Initial Analysis
        ->
    Critique
        ->
    APPROVE or REVISE
        ->
    Refine if necessary
        ->
    Final Analysis
    """

    print("\n[Reflection] Reviewing initial analysis...")

    reflection = reflect_on_analysis(
        job,
        user_skills,
        initial_analysis
    )

    print("\n[Reflection] Critic result:")
    print(reflection)

    # Normalize the response for reliable decision checking
    reflection_upper = reflection.upper()

    # If the critic detects a problem, refine the analysis
    if "DECISION: REVISE" in reflection_upper:

        print("\n[Reflection] Revision required.")
        print("[Reflection] Refining analysis...")

        refined_analysis = refine_analysis(
            job,
            user_skills,
            initial_analysis,
            reflection
        )

        print("[Reflection] Refinement completed.")

        return refined_analysis

    # If the critic approves it, keep the original analysis
    if "DECISION: APPROVE" in reflection_upper:

        print("\n[Reflection] Analysis approved.")

        return initial_analysis

    # Fallback if Gemini does not follow the requested format
    print(
        "\n[Reflection] No clear APPROVE/REVISE decision detected. "
        "Keeping the initial analysis."
    )

    return initial_analysis